hugo:
  image: jojomi/hugo:latest
  volumes:
    - ./jugf-site:/src
    - ./jugf-site/output:/output
  ports:
    - 1313:1313
  environment:
    - HUGO_REFRESH_TIME=20
    - HUGO_THEME=ananke
    - HUGO_BASEURL=http://cyberdyne-101.net
  restart: always

web:
  image: jojomi/nginx-static
  volumes:
    - ./output:/var/www
  ports:
    - 80:80
  restart: always